# Generated by Django 4.0.5 on 2022-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch_count', models.PositiveSmallIntegerField(default=0)),
                ('usd_buy', models.FloatField()),
                ('usd_sell', models.FloatField()),
                ('euro_buy', models.FloatField()),
                ('euro_sell', models.FloatField()),
            ],
        ),
    ]
