# Generated by Django 4.0.5 on 2022-07-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='rub_buy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='rub_sell',
            field=models.FloatField(null=True),
        ),
    ]
