# Generated by Django 4.0.5 on 2022-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch_models', '0002_bank_rub_buy_bank_rub_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='euro_buy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='euro_sell',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='usd_buy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='usd_sell',
            field=models.FloatField(null=True),
        ),
    ]
